services:
  postgres-db:
    image: postgis/postgis:latest
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '${WS_PORT}:${WS_PORT}'
    volumes:
      - .:/app
    links:
      - "postgres-db"
    depends_on:
      - "postgres-db"
    command: [ "./wait-for-service-start.sh", "postgres-db:5432", "--", "npm", "run", "dev" ]
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432

volumes:
  postgres-data:
