const ERROR_TYPES = {
  INTERNAL_FAILURE: 'ERR_INTERNAL_FAILURE',
  INVALID_DATA_FORMAT: 'ERR_INVALID_DATA_FORMAT',
  UNKNOWN_EVENT: 'ERR_UNKNOWN_EVENT',
  UNAUTHORISED: 'ERR_UNAUTHORISED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  CONFLICT: 'ERR_CONFLICT',
  REQUEST_TIMED_OUT: 'ERR_REQUEST_TIMED_OUT',
  PROCESSING_FAILED: 'ERR_PROCESSING_FAILED',
};

export default ERROR_TYPES;

